[workspace]
members = [
    "query",
    "substreams",
]

[patch.crates-io]
substreams = { git = "https://github.com/streamingfast/substreams-rs", branch = "develop" }

[profile.release]
lto = true
opt-level = 3
strip = "debuginfo"